### ISSUE TITLE
Incorrect 📚 Resources links assigned to a project on your lists of JS projects page

### ISSUE THREAD

**Issue by Stan015** [flowforfrank/webtips#31]
Being a huge fan of this amazing website, I do come to learn new stuffs or get a project idea to work on. 
On your page titled: [**_100 JavaScript Project Ideas_**](https://webtips.dev/100-javascript-project-ideas), I tried to access the resources on a project on the list and noticed it was assigned a wrong 📚 Resources links: both the Design and Tutorial Link.

Project list number and title: # 1 — Create a To-Do App

Issue: 📚 Resources:
- figma [Design](https://www.figma.com/community/file/881195330537323050)
- youtube [Tutorial: Build a calculator with JavaScript](https://www.youtube.com/watch?v=j59qQ7YWLxw)
<img width="1728" alt="Screenshot 2024-03-15 at 9 43 51 AM" src="https://github.com/flowforfrank/webtips/assets/87153210/acc841bb-3271-44b4-aa41-5212b9cf6192">

The two links contains design of another project (calculator project) and a youtube link of a calculator development tutorial. 

Correcting this is by simply replacing the link of the figma design with a Todo design by searching for a design file on figma community or any other design community, and replacing the youtube tutorial video with the appropriate tutorial for the todo app.

**Comment by flowforfrank** [comment]
Hey @Stan015!

Thank you for your kind and in-depth comment! I regularly update this post and it looks like I mistakenly updated the links with incorrect ones, thank you for spotting this issue! I updated the links back to the old, correct ones.

**Comment by Stan015** [comment]
Corrected! Thank you for your good works at webtips. Well done.
